<?php

/**
 * BaseSocket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pid
 * @property string $host
 * @property string $port
 * @property string $status
 * @property Doctrine_Collection $Room
 * @property Doctrine_Collection $Game
 * @property Doctrine_Collection $Messages
 * @property Doctrine_Collection $OnlineUsers
 * 
 * @method integer             getPid()         Returns the current record's "pid" value
 * @method string              getHost()        Returns the current record's "host" value
 * @method string              getPort()        Returns the current record's "port" value
 * @method string              getStatus()      Returns the current record's "status" value
 * @method Doctrine_Collection getRoom()        Returns the current record's "Room" collection
 * @method Doctrine_Collection getGame()        Returns the current record's "Game" collection
 * @method Doctrine_Collection getMessages()    Returns the current record's "Messages" collection
 * @method Doctrine_Collection getOnlineUsers() Returns the current record's "OnlineUsers" collection
 * @method Socket              setPid()         Sets the current record's "pid" value
 * @method Socket              setHost()        Sets the current record's "host" value
 * @method Socket              setPort()        Sets the current record's "port" value
 * @method Socket              setStatus()      Sets the current record's "status" value
 * @method Socket              setRoom()        Sets the current record's "Room" collection
 * @method Socket              setGame()        Sets the current record's "Game" collection
 * @method Socket              setMessages()    Sets the current record's "Messages" collection
 * @method Socket              setOnlineUsers() Sets the current record's "OnlineUsers" collection
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSocket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('socket');
        $this->hasColumn('pid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('host', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('port', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Room', array(
             'local' => 'id',
             'foreign' => 'socket_id'));

        $this->hasMany('Game', array(
             'local' => 'id',
             'foreign' => 'socket_id'));

        $this->hasMany('Message as Messages', array(
             'local' => 'id',
             'foreign' => 'socket_id'));

        $this->hasMany('Online as OnlineUsers', array(
             'local' => 'id',
             'foreign' => 'socket_id'));
    }
}