<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $official_name
 * @property string $name
 * @property string $nickname
 * @property string $logo
 * @property string $initials
 * @property string $description
 * @property Doctrine_Collection $sfGuardUsers
 * @property Doctrine_Collection $Game
 * 
 * @method string              getOfficialName()  Returns the current record's "official_name" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getNickname()      Returns the current record's "nickname" value
 * @method string              getLogo()          Returns the current record's "logo" value
 * @method string              getInitials()      Returns the current record's "initials" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method Doctrine_Collection getSfGuardUsers()  Returns the current record's "sfGuardUsers" collection
 * @method Doctrine_Collection getGame()          Returns the current record's "Game" collection
 * @method Team                setOfficialName()  Sets the current record's "official_name" value
 * @method Team                setName()          Sets the current record's "name" value
 * @method Team                setNickname()      Sets the current record's "nickname" value
 * @method Team                setLogo()          Sets the current record's "logo" value
 * @method Team                setInitials()      Sets the current record's "initials" value
 * @method Team                setDescription()   Sets the current record's "description" value
 * @method Team                setSfGuardUsers()  Sets the current record's "sfGuardUsers" collection
 * @method Team                setGame()          Sets the current record's "Game" collection
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('official_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nickname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('initials', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as sfGuardUsers', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('Game', array(
             'local' => 'id',
             'foreign' => 'home_team_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}