<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $socket_id
 * @property integer $user_id
 * @property string $socket_user_id
 * @property string $type
 * @property string $message
 * @property Socket $Socket
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Turn
 * 
 * @method integer             getSocketId()       Returns the current record's "socket_id" value
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method string              getSocketUserId()   Returns the current record's "socket_user_id" value
 * @method string              getType()           Returns the current record's "type" value
 * @method string              getMessage()        Returns the current record's "message" value
 * @method Socket              getSocket()         Returns the current record's "Socket" value
 * @method sfGuardUser         getUser()           Returns the current record's "User" value
 * @method Doctrine_Collection getTurn()           Returns the current record's "Turn" collection
 * @method Message             setSocketId()       Sets the current record's "socket_id" value
 * @method Message             setUserId()         Sets the current record's "user_id" value
 * @method Message             setSocketUserId()   Sets the current record's "socket_user_id" value
 * @method Message             setType()           Sets the current record's "type" value
 * @method Message             setMessage()        Sets the current record's "message" value
 * @method Message             setSocket()         Sets the current record's "Socket" value
 * @method Message             setUser()           Sets the current record's "User" value
 * @method Message             setTurn()           Sets the current record's "Turn" collection
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('socket_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('socket_user_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Socket', array(
             'local' => 'socket_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Turn', array(
             'local' => 'id',
             'foreign' => 'message_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}