<?php

/**
 * BaseMovement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $game_id
 * @property integer $user_id
 * @property string $message
 * @property Game $Game
 * @property sfGuardUser $User
 * 
 * @method integer     getGameId()  Returns the current record's "game_id" value
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method string      getMessage() Returns the current record's "message" value
 * @method Game        getGame()    Returns the current record's "Game" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method Movement    setGameId()  Sets the current record's "game_id" value
 * @method Movement    setUserId()  Sets the current record's "user_id" value
 * @method Movement    setMessage() Sets the current record's "message" value
 * @method Movement    setGame()    Sets the current record's "Game" value
 * @method Movement    setUser()    Sets the current record's "User" value
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMovement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movement');
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}