<?php

/**
 * BaseTurn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $game_id
 * @property integer $user_id
 * @property integer $message_id
 * @property integer $number
 * @property Game $Game
 * @property sfGuardUser $User
 * @property Message $Message
 * 
 * @method integer     getGameId()     Returns the current record's "game_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method integer     getMessageId()  Returns the current record's "message_id" value
 * @method integer     getNumber()     Returns the current record's "number" value
 * @method Game        getGame()       Returns the current record's "Game" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method Message     getMessage()    Returns the current record's "Message" value
 * @method Turn        setGameId()     Sets the current record's "game_id" value
 * @method Turn        setUserId()     Sets the current record's "user_id" value
 * @method Turn        setMessageId()  Sets the current record's "message_id" value
 * @method Turn        setNumber()     Sets the current record's "number" value
 * @method Turn        setGame()       Sets the current record's "Game" value
 * @method Turn        setUser()       Sets the current record's "User" value
 * @method Turn        setMessage()    Sets the current record's "Message" value
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTurn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('turn');
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('message_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Message', array(
             'local' => 'message_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}