<?php

/**
 * BaseRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $socket_id
 * @property string $title
 * @property string $description
 * @property sfGuardUser $User
 * @property Socket $Socket
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getSocketId()    Returns the current record's "socket_id" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Socket      getSocket()      Returns the current record's "Socket" value
 * @method Room        setUserId()      Sets the current record's "user_id" value
 * @method Room        setSocketId()    Sets the current record's "socket_id" value
 * @method Room        setTitle()       Sets the current record's "title" value
 * @method Room        setDescription() Sets the current record's "description" value
 * @method Room        setUser()        Sets the current record's "User" value
 * @method Room        setSocket()      Sets the current record's "Socket" value
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('socket_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Socket', array(
             'local' => 'socket_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}