<?php

/**
 * BaseOnline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $socket_user_id
 * @property string $status
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()         Returns the current record's "user_id" value
 * @method string      getSocketUserId()   Returns the current record's "socket_user_id" value
 * @method string      getStatus()         Returns the current record's "status" value
 * @method sfGuardUser getUser()           Returns the current record's "User" value
 * @method Online      setUserId()         Sets the current record's "user_id" value
 * @method Online      setSocketUserId()   Sets the current record's "socket_user_id" value
 * @method Online      setStatus()         Sets the current record's "status" value
 * @method Online      setUser()           Sets the current record's "User" value
 * 
 * @package    elastball
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOnline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('online');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('socket_user_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}