<?php

/**
 * MovementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Movement');
    }
}