<?php

/**
 * OnlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OnlineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OnlineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Online');
    }
}