<?php

/**
 * SocketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SocketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SocketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Socket');
    }
}