function Ball(a,b,e,d){0<arguments.length?(this.id=a,this.radius=b,this.x=e,this.y=d):(this.id=0,this.radius=10,this.y=this.x=0);this.velocityy=this.velocityx=this.angle=this.speed=0;this.mass=8*this.radius;this.nextx=this.x;this.nexty=this.y;this.speed=this.rangle=this.anglespeed=0;this.center=new Point2D(this.x,this.y);this.startPoint=new Point2D(this.x,this.y)}Ball.prototype.draw=function(){return!0};
function Field(a,b,e){if(a)this.game=a;this.width=b?b:800;this.height=e?e:1200;this.radiusBall=10;this.radiusCorner=20;this.radiusMidfield=100;this.penalty=120;this.areaHeight=180;this.areaWidth=440;this.goalAreaHeight=60;this.goalAreaWidth=200;this.goalHeight=40;this.goalWidth=140}Field.prototype.draw=function(){return!0};var mouse;
function Game(a){this.zoom=1;this.canvas=a;this.context=a.getContext("2d");this.context.scale(this.zoom,this.zoom);this.context.fillStyle="#EEEEEE";this.width=1050;this.height=1400;this.angle2=this.angle1=this._y=this._x=0;this.minSize=this.maxSize=this.numBalls=25;this.maxSpeed=this.maxSize+5;this.minSpeed=0.01;this.friction=0.06;this.running=!1;this.currentPlayer=this.selected_ball=null;this.balls=[];this.keepers=[];this.team1=[];this.team2=[];this.is_moving=!1;var b=this;this.field=new Field(b);
this.teamHome=new Team("","","","rgba(218, 37, 29, 0.7)");this.teamHome.formation=[[300,250],[450,250],[600,250],[750,250],[200,600],[350,600],[850,600],[700,600],[490,625],[570,615]];this.teamAway=new Team("","","","rgba(74, 133, 255, 0.7)");this.teamAway.formation=[[300,1050],[450,1050],[600,1050],[750,1050],[200,700],[350,700],[850,700],[700,700],[450,800],[600,800]];for(a=0;a<this.numBalls;a++){tempRadius=25;tempBall={id:a,x:0,y:0,radius:tempRadius,speed:0,angle:0,velocityx:0,velocityy:0,mass:8*
tempRadius,nextx:0,nexty:0,anglespeed:0,rangle:0,speed:0,startPoint:new Point2D(0,0),moveble:!0};if(0>=this.balls.length)tempBall.isBall=!0,tempBall.radius=5,tempBall.x=this.width/2,tempBall.y=this.height/2,tempBall.nextx=tempBall.x,tempBall.nexty=tempBall.y,tempBall.startPoint=new Point2D(tempBall.x,tempBall.y),tempBall.mass=10;else{if(4>=a){var e=(this.width-this.field.width)/2,d=(this.height-this.field.height)/2,g=this.field.width/2,f=e+g-this.field.goalWidth/2;if(1==a)tempBall.x=f,tempBall.y=
d,tempBall.nextx=f,tempBall.nexty=d,tempBall.startPoint=new Point2D(f,d);else if(2==a)tempBall.x=f+this.field.goalWidth,tempBall.y=d,tempBall.nextx=f+this.field.goalWidth,tempBall.nexty=d,tempBall.startPoint=new Point2D(f+this.field.goalWidth,d);else if(3==a)tempBall.x=f,tempBall.y=d+this.field.height,tempBall.nextx=f,tempBall.nexty=d+this.field.height,tempBall.startPoint=new Point2D(f,d+this.field.height);else if(4==a)tempBall.x=f+this.field.goalWidth,tempBall.y=d+this.field.height,tempBall.nextx=
f+this.field.goalWidth,tempBall.nexty=d+this.field.height,tempBall.startPoint=new Point2D(f+this.field.goalWidth,d+this.field.height);this.context.fillRect(e+g-this.field.goalWidth/2,d+this.field.height,this.field.goalWidth,this.field.goalHeight);tempBall.isBall=!1;tempBall.radius=4;tempBall.moveble=!1;tempBall.mass=1E3}else a<=(this.numBalls-5)/2+4?(e=a-5,console.log("team1>>"+e),tempBall.team=this.teamHome,tempBall.x=this.teamHome.formation[e][0],tempBall.y=this.teamHome.formation[e][1],tempBall.nextx=
this.teamHome.formation[e][0],tempBall.nexty=this.teamHome.formation[e][1],tempBall.startPoint=new Point2D(tempBall.x,tempBall.y),this.team1.push(tempBall)):(e=a-(this.numBalls-5)/2-5,console.log("team2>>"+e),tempBall.team=this.teamAway,tempBall.x=this.teamAway.formation[e][0],tempBall.y=this.teamAway.formation[e][1],tempBall.nextx=this.teamAway.formation[e][0],tempBall.nexty=this.teamAway.formation[e][1],tempBall.startPoint=new Point2D(tempBall.x,tempBall.y),this.team2.push(tempBall));tempBall.anglespeed=
0;tempBall.rangle=0;tempBall.velocityx=0;tempBall.velocityy=0;tempBall.speed=0}this.balls.push(tempBall);console.log("balls length>>"+this.balls.length)}this._x=0;this._y=-this.height/2+this.canvas.height/2;keeper1={id:1,x:this.canvas.width/2-45,y:90,width:90,height:30,angle:0,mass:1E3,team:1};this.keepers.push(keeper1);keeper2={id:2,x:this.canvas.width/2-45,y:this.canvas.width-90,width:90,height:30,angle:0,mass:1E3,team:2};this.keepers.push(keeper2);b=this;this.mouse=new Mouse(b);window.requestAnimFrame=
function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();(function i(){requestAnimFrame(i,this.canvas);b.draw()})()}
Game.prototype.draw=function(){this.context.fillStyle="#EEEEEE";this.context.fillRect(0,0,this.canvas.width,this.canvas.height);this.context.strokeStyle="#000000";this.context.strokeRect(1,1,this.canvas.width-2,this.canvas.height-2);this.running&&(this.update(),this.collide(),this.testWalls(),this.testKeepers(),this.testNet());this.drawField();this.render()};
Game.prototype.update=function(){for(var a=!1,b=0;b<this.balls.length;b++){ball=this.balls[b];ball.velocityx-=ball.velocityx*this.friction;ball.velocityy-=ball.velocityy*this.friction;ball.nextx=ball.x+=ball.velocityx;ball.nexty=ball.y+=ball.velocityy;if(Math.abs(ball.velocityx)>this.minSpeed||Math.abs(ball.velocityy)>this.minSpeed)a=!0;if(ball.velocityx>this.maxSpeed)ball.velocityx=this.maxSpeed;if(ball.velocityy>this.maxSpeed)ball.velocityy=this.maxSpeed}if(!this.is_moving)if(this._x=0,this._y+=
this.canvas.height/2+Math.abs(this._y)-this.balls[0].y,0<this._y)this._y=0;else if(Math.abs(this._y)+this.canvas.height>this.height)this._y=-this.height+this.canvas.height;this.running=a};
Game.prototype.render=function(){var a,b;this.context.save();this.context.translate(this._x,this._y);console.log(this.mouse.y+", "+this.mouse.getY());for(var e=0;e<this.balls.length;e++){a=this.balls[e];b=this.mouse.isOverBall(a);a.x=a.nextx;a.y=a.nexty;this.context.save();this.context.fillStyle="rgba(255, 255, 255, 1)";if(a.team){if(this.context.fillStyle=a.team.color,this.context.beginPath(),this.context.translate(a.x,a.y),this.context.shadowColor="black",this.context.arc(0,0,a.radius,0,2*Math.PI,
!0),this.context.fill(),this.context.shadowColor="rgba(0, 0, 0, 0.5)",this.context.shadowOffsetX=1,this.context.shadowOffsetY=3,this.context.shadowBlur=2,this.context.fill(),b&&!this.mouse.down)document.body.style.cursor="hand",this.context.fillStyle="rgba(250, 250, 250, 0.3)",this.context.arc(0,0,a.radius,0,2*Math.PI,!0),this.context.fill()}else{if(a.isBall){var d=Math.sqrt(a.velocityx*a.velocityx+a.velocityy*a.velocityy);this.context.beginPath();this.context.translate(a.x,a.y);this.context.arc(0,
0,a.radius,0,2*Math.PI,!0);this.context.stroke();this.context.fill();this.context.shadowColor="rgba(0, 0, 0, 0.5)";this.context.shadowOffsetX=1*d;this.context.shadowOffsetY=1*d;this.context.shadowBlur=3}else this.context.beginPath(),this.context.translate(a.x,a.y),this.context.arc(0,0,a.radius,0,2*Math.PI,!0),this.context.stroke();this.context.fill()}this.context.restore();this.context.closePath();if(null==this.selected_ball&&b&&this.mouse.down&&a.team&&!this.is_moving)this.selected_ball=a,this.currentPlayer=
e,document.body.style.cursor="hand"}if(0!=this.mouse.down_x&&0!=this.mouse.down_y&&null!=this.selected_ball&&(document.body.style.cursor="none","move"!=this.selected_ball.id&&"rotate"!=this.selected_ball.id))d=this.mouse.x-this.selected_ball.x,a=this.mouse.y-this.selected_ball.y,e=this.selected_ball.x-d,a=this.selected_ball.y-a,b=this.selected_ball.x-e,d=this.selected_ball.y-a,this.context.beginPath(),this.context.lineWidth=12,this.context.strokeStyle="rgba(255, 0, 0, 0.5)",this.context.moveTo(this.mouse.x,
this.mouse.y),this.context.lineTo(this.selected_ball.x,this.selected_ball.y),this.context.stroke(),this.context.lineWidth=6,this.context.strokeStyle="rgba(255, 0, 0, 0.3)",this.context.lineTo(e,a),this.context.stroke(),this.context.lineWidth=3,this.context.strokeStyle="rgba(255, 0, 0, 0.1)",this.context.lineTo(e-b,a-d),this.context.stroke();for(e=0;e<this.keepers.length;e++){keeper=this.keepers[e];this.context.fillStyle=keeper.team.color;this.context.strokeStyle="rgba(255,255,255,1)";rp1=new Point2D(keeper.x-
keeper.width/2*Math.cos(keeper.angle)+keeper.height/2*Math.sin(keeper.angle),keeper.y-keeper.height/2*Math.cos(keeper.angle)-keeper.width/2*Math.sin(keeper.angle));rp2=new Point2D(keeper.x+keeper.width/2*Math.cos(keeper.angle)+keeper.height/2*Math.sin(keeper.angle),keeper.y-keeper.height/2*Math.cos(keeper.angle)+keeper.width/2*Math.sin(keeper.angle));rp3=new Point2D(keeper.x+keeper.width/2*Math.cos(keeper.angle)-keeper.height/2*Math.sin(keeper.angle),keeper.y+keeper.height/2*Math.cos(keeper.angle)+
keeper.width/2*Math.sin(keeper.angle));rp4=new Point2D(keeper.x-keeper.width/2*Math.cos(keeper.angle)-keeper.height/2*Math.sin(keeper.angle),keeper.y+keeper.height/2*Math.cos(keeper.angle)-keeper.width/2*Math.sin(keeper.angle));b=this.mouse.isOverRect(rp1,rp2,rp3,rp4);tempBall={id:"move",x:keeper.x,y:keeper.y,nextx:keeper.x,nexty:keeper.y,radius:21,k:e};overMoveKeeper=this.mouse.isOverBall(tempBall);if(null==this.selected_ball&&overMoveKeeper&&this.mouse.down)this.selected_ball=tempBall;tempBall=
{id:"rotate",x:rp2.x,y:rp2.y,nextx:rp2.x,nexty:rp2.y,radius:21,k:e};overRotateKeeper=this.mouse.isOverBall(tempBall);if(null==this.selected_ball&&overRotateKeeper&&this.mouse.down)this.selected_ball=tempBall;if(null!=this.selected_ball){if("move"==this.selected_ball.id&&this.mouse.down&&this.selected_ball.k==e&&0!=this.mouse.down_x&&0!=this.mouse.down_y)keeper.x=this.mouse.x,keeper.y=this.mouse.y;if("rotate"==this.selected_ball.id&&this.mouse.down&&this.selected_ball.k==e&&0!=this.mouse.down_x&&0!=
this.mouse.down_y)d=this.mouse.x-keeper.x+21,a=this.mouse.y-keeper.y+21,keeper.angle=Math.atan2(a,d)}this.context.save();this.context.beginPath();this.context.moveTo(rp1.x,rp1.y);this.context.lineTo(rp2.x,rp2.y);this.context.lineTo(rp3.x,rp3.y);this.context.lineTo(rp4.x,rp4.y);this.context.lineTo(rp1.x,rp1.y);this.context.closePath();this.context.fill();this.context.shadowColor="rgba(0, 0, 0, 1)";this.context.shadowOffsetX=3;this.context.shadowOffsetY=6;this.context.shadowBlur=5;this.context.fill();
this.context.restore();if(b||overMoveKeeper||overRotateKeeper)this.context.save(),this.context.beginPath(),this.context.strokeStyle=overMoveKeeper?"rgba(255, 255, 0, 1)":"rgba(255, 0, 0, 0.5)",this.context.arc(keeper.x,keeper.y,21,0,2*Math.PI,!0),this.context.stroke(),this.context.closePath(),this.context.beginPath(),this.context.strokeStyle=overRotateKeeper?"rgba(255, 255, 0, 1)":"rgba(255, 0, 0, 0.5)",this.context.arc(rp2.x,rp2.y,21,0,2*Math.PI,!0),this.context.closePath(),this.context.stroke(),
this.context.restore();if(null==this.selected_ball&&this.mouse.down&&this.mouse.down_y!=this.mouse.y)if(this._y-=0.1*(this.mouse.down_y-this.mouse.y),this.is_moving=!0,0<this._y)this._y=0;else if(Math.abs(this._y)+this.canvas.height>this.height)this._y=-this.height+this.canvas.height}this.context.restore()};
Game.prototype.drawField=function(){this.context.save();this.context.translate(this._x,this._y);this.context.strokeStyle="#FFF";this.context.fillStyle="#FFF";this.context.lineWidth=3;var a=(this.width-this.field.width)/2,b=(this.height-this.field.height)/2,e=this.field.width/2,d=this.field.height/2;this.context.save();this.context.fillStyle="rgba(82,132,61, 1)";this.context.fillRect(0,0,this.width,this.height);this.context.fillStyle="rgba(49,107,56, 1)";for(var g=this.field.height/15,f=0;f<this.field.height/
g;f++)1!=f%2&&this.context.fillRect(a,b+f*g,this.field.width,g);this.context.restore();this.context.strokeRect(a,b,this.field.width,this.field.height);this.context.moveTo(a,b+d);this.context.lineTo(a+this.field.width,b+d);this.context.stroke();this.context.beginPath();this.context.arc(a+e,b+d,this.field.radiusBall,0,2*Math.PI,!0);this.context.closePath();this.context.fill();this.context.beginPath();this.context.arc(a+e,b+d,this.field.radiusMidfield,0,2*Math.PI,!0);this.context.closePath();this.context.stroke();
d=a+e-this.field.goalWidth/2;this.context.save();this.context.lineWidth=8;this.context.fillStyle="rgba(105, 105, 105, 0.8)";this.context.moveTo(d,b);this.context.lineTo(d,b-this.field.goalHeight);this.context.lineTo(d+this.field.goalWidth,b-this.field.goalHeight);this.context.lineTo(d+this.field.goalWidth,b);this.context.stroke();this.context.moveTo(d,b+this.field.height);this.context.lineTo(d,b+this.field.height+this.field.goalHeight);this.context.lineTo(d+this.field.goalWidth,b+this.field.height+
this.field.goalHeight);this.context.lineTo(d+this.field.goalWidth,b+this.field.height);this.context.stroke();this.context.restore();this.context.strokeRect((this.field.width-this.field.areaWidth)/2+a,b,this.field.areaWidth,this.field.areaHeight);this.context.strokeRect((this.field.width-this.field.goalAreaWidth)/2+a,b,this.field.goalAreaWidth,this.field.goalAreaHeight);this.context.beginPath();this.context.arc(a+e,b+this.field.penalty,this.field.radiusMidfield,0.64,Math.PI-0.64,!1);this.context.stroke();
this.context.beginPath();this.context.arc(a+e,b+this.field.penalty,this.field.radiusBall,0,2*Math.PI,!0);this.context.closePath();this.context.fill();this.context.strokeRect((this.field.width-this.field.areaWidth)/2+a,b+this.field.height-this.field.areaHeight,this.field.areaWidth,this.field.areaHeight);this.context.strokeRect((this.field.width-this.field.goalAreaWidth)/2+a,b+this.field.height-this.field.goalAreaHeight,this.field.goalAreaWidth,this.field.goalAreaHeight);this.context.beginPath();this.context.arc(a+
e,b+this.field.height-this.field.penalty,this.field.radiusMidfield,-0.64,Math.PI+0.64,!0);this.context.stroke();this.context.beginPath();this.context.arc(a+e,b+this.field.height-this.field.penalty,this.field.radiusBall,0,2*Math.PI,!0);this.context.closePath();this.context.fill();this.context.beginPath();this.context.arc(a,b,this.field.radiusCorner,0,Math.PI/2,!1);this.context.stroke();this.context.beginPath();this.context.arc(a+this.field.width,b,this.field.radiusCorner,Math.PI/2,Math.PI,!1);this.context.stroke();
this.context.beginPath();this.context.arc(a,b+this.field.height,this.field.radiusCorner,0,-Math.PI/2,!0);this.context.stroke();this.context.beginPath();this.context.arc(a+this.field.width,b+this.field.height,this.field.radiusCorner,-Math.PI/2,-Math.PI,!0);this.context.stroke();this.context.restore()};
Game.prototype.testWalls=function(){for(var a,b=this.canvas.width,e=!1,d=0;d<this.balls.length;d++){a=this.balls[d];if(a.nextx+a.radius>b)a.velocityx*=-1,a.nextx=b-a.radius,e=!0;else if(0>a.nextx-a.radius)a.velocityx*=-1,a.nextx=a.radius,e=!0;if(e)a.startPoint=new Point2D(a.nextx,a.nexty)}};
Game.prototype.collide=function(){for(var a,b,e,d,g,f=0;f<this.balls.length;f++){a=this.balls[f];for(var h=f+1;h<this.balls.length;h++)if(b=this.balls[h],this.hitTestCircle(a,b)){if(0==a.id)d=b.id,g=b.team;if((game.currentPlayer==f||game.currentPlayer==h)&&!e)e=b.id;this.collideBalls(a,b)}}this.turn=g;this.first_collision=e;this.last_collision=d};
Game.prototype.collideBalls=function(a,b){var e=Math.atan2(a.nexty-b.nexty,a.nextx-b.nextx),d=Math.sqrt(a.velocityx*a.velocityx+a.velocityy*a.velocityy),g=Math.sqrt(b.velocityx*b.velocityx+b.velocityy*b.velocityy),f=Math.atan2(a.velocityy,a.velocityx),h=Math.atan2(b.velocityy,b.velocityx),i=d*Math.cos(f-e),d=d*Math.sin(f-e),f=g*Math.cos(h-e),g=g*Math.sin(h-e),h=((a.mass-b.mass)*i+(b.mass+b.mass)*f)/(a.mass+b.mass),i=((a.mass+a.mass)*i+(b.mass-a.mass)*f)/(a.mass+b.mass);if(a.moveble)a.velocityx=Math.cos(e)*
h+Math.cos(e+Math.PI/2)*d,a.velocityy=Math.sin(e)*h+Math.sin(e+Math.PI/2)*d,a.nextx=a.nextx+=a.velocityx,a.nexty=a.nexty+=a.velocityy,a.startPoint=new Point2D(a.nextx,a.nexty);if(b.moveble)b.velocityx=Math.cos(e)*i+Math.cos(e+Math.PI/2)*g,b.velocityy=Math.sin(e)*i+Math.sin(e+Math.PI/2)*g,b.nextx=b.nextx+=b.velocityx,b.nexty=b.nexty+=b.velocityy,b.startPoint=new Point2D(b.nextx,b.nexty)};
Game.prototype.hitTestCircle=function(a,b){var e=!1,d=a.nextx-b.nextx,g=a.nexty-b.nexty;d*d+g*g<=(a.radius+b.radius)*(a.radius+b.radius)&&(e=!0);return e};Game.prototype.pointIsOverRect=function(a,b,e,d,g){var f=[];f[0]=b;f[1]=e;f[2]=d;f[3]=g;a=new Point2D(this.mouse.x,this.mouse.y);b=!1;e=-1;d=f.length;for(g=d-1;++e<d;g=e)(f[e].y<=a.y&&a.y<f[g].y||f[g].y<=a.y&&a.y<f[e].y)&&a.x<(f[g].x-f[e].x)*(a.y-f[e].y)/(f[g].y-f[e].y)+f[e].x&&(b=!b);return b};
Game.prototype.testKeepers=function(){for(var a,b=0;b<this.balls.length;b++){a=this.balls[b];for(var e=0;e<this.keepers.length;e++){keeper=this.keepers[e];p1=new Point2D(keeper.x-(keeper.width+a.radius/2)*Math.cos(keeper.angle)+(keeper.height+a.radius/2)*Math.sin(keeper.angle),keeper.y-(keeper.height+a.radius/2)*Math.cos(keeper.angle)-(keeper.width+a.radius/2)*Math.sin(keeper.angle));p2=new Point2D(keeper.x+(keeper.width+a.radius/2)*Math.cos(keeper.angle)+(keeper.height+a.radius/2)*Math.sin(keeper.angle),
keeper.y-(keeper.height+a.radius/2)*Math.cos(keeper.angle)+(keeper.width+a.radius/2)*Math.sin(keeper.angle));p3=new Point2D(keeper.x+(keeper.width+a.radius/2)*Math.cos(keeper.angle)-(keeper.height+a.radius/2)*Math.sin(keeper.angle),keeper.y+(keeper.height+a.radius/2)*Math.cos(keeper.angle)+(keeper.width+a.radius/2)*Math.sin(keeper.angle));p4=new Point2D(keeper.x-(keeper.width+a.radius/2)*Math.cos(keeper.angle)-(keeper.height+a.radius/2)*Math.sin(keeper.angle),keeper.y+(keeper.height+a.radius/2)*Math.cos(keeper.angle)-
(keeper.width+a.radius/2)*Math.sin(keeper.angle));p1n=new Point2D(keeper.x-keeper.width/2*Math.cos(keeper.angle)+keeper.height/2*Math.sin(keeper.angle),keeper.y-keeper.height/2*Math.cos(keeper.angle)-keeper.width/2*Math.sin(keeper.angle));p2n=new Point2D(keeper.x+keeper.width/2*Math.cos(keeper.angle)+keeper.height/2*Math.sin(keeper.angle),keeper.y-keeper.height/2*Math.cos(keeper.angle)+keeper.width/2*Math.sin(keeper.angle));p3n=new Point2D(keeper.x+keeper.width/2*Math.cos(keeper.angle)-keeper.height/
2*Math.sin(keeper.angle),keeper.y+keeper.height/2*Math.cos(keeper.angle)+keeper.width/2*Math.sin(keeper.angle));p4n=new Point2D(keeper.x-keeper.width/2*Math.cos(keeper.angle)-keeper.height/2*Math.sin(keeper.angle),keeper.y+keeper.height/2*Math.cos(keeper.angle)-keeper.width/2*Math.sin(keeper.angle));p1=new Point2D(p1n.x-a.radius,p1n.y-a.radius);p2=new Point2D(p2n.x+a.radius,p2n.y-a.radius);p3=new Point2D(p3n.x+a.radius,p3n.y+a.radius);p4=new Point2D(p4n.x-a.radius,p4n.y+a.radius);var d=p2.y-p1.y/
p2.x-p1.x;if(!this.pointIsOverRect(new Point2D(a.nextx,a.nexty),p1,p2,p3,p4)){b1=new Point2D(a.startPoint.x,a.startPoint.y);b2=new Point2D(a.x,a.y);new Point2D(a.startPoint.x-a.radius,a.startPoint.y-a.radius);c2=new Point2D(a.nextx-a.radius,a.nexty-a.radius);d1=new Point2D(a.startPoint.x,a.startPoint.y);d2=new Point2D(a.nextx+a.radius,a.nexty+a.radius);var g=1;c=intersectLineLine(b1,b2,p1,p2);c||(g=3,c=intersectLineLine(b1,b2,p3,p4));c||(g=4,c=intersectLineLine(b1,b2,p4,p1));c||(g=2,c=intersectLineLine(b1,
b2,p2,p3));if(c){var f={x:0,y:0,radius:a.radius,speed:0,velocityx:0,velocityy:0,mass:999999,nextx:0,nexty:0,speed:0},h=!1,i=!1;if(c.x<p1n.x&&c.y<p1n.y){if(i=!0,h=intersectCircleLine(p1n,a.radius,b1,b2))f.x=p1n.x,f.y=p1n.y,f.nextx=h.x,f.nexty=h.y}else if(c.x>p2n.x&&c.y<p2n.y){if(i=!0,h=intersectCircleLine(p2n,a.radius,b1,b2))f.x=p2n.x,f.y=p2n.y,f.nextx=h.x,f.nexty=h.y}else if(c.x>p3n.x&&c.y>p3n.y){if(i=!0,h=intersectCircleLine(p3n,a.radius,b1,b2))f.x=p3n.x,f.y=p3n.y,f.nextx=h.x,f.nexty=h.y}else if(c.x<
p4n.x&&c.y>p4n.y&&(i=!0,h=intersectCircleLine(p4n,a.radius,b1,b2)))f.x=p4n.x,f.y=p4n.y,f.nextx=h.x,f.nexty=h.y;if(h)c=h,f.velocityx=0,f.velocityy=0,f.nextx=f.x,f.nexty=f.y,this.collideBalls(f,a);else if(!i){f.mass=999999999999;f.radius=0;f.x=c.x;f.y=c.y;f.velocityx=0;f.velocityy=0;if(1==g)f.y=c.y-a.radius;else if(3==g)f.y=c.x*d,f.x=c.x;else if(2==g)f.x=c.x-a.radius;else if(4==g)f.x=c.x+a.radius;f.nextx=f.x;f.nexty=f.y;var d=a,h=Math.atan2(d.y-f.nexty,d.x-f.nextx),j=Math.sqrt(d.velocityx*d.velocityx+
d.velocityy*d.velocityy),k=Math.atan2(d.velocityy,d.velocityx),l=Math.atan2(f.velocityy,f.velocityx),i=j*Math.cos(k-h),j=j*Math.sin(k-h),m=0*Math.cos(l-h),k=0*Math.sin(l-h),l=((d.mass-f.mass)*i+(f.mass+f.mass)*m)/(d.mass+f.mass),i=((d.mass+d.mass)*i+(f.mass-d.mass)*m)/(d.mass+f.mass);d.velocityx=Math.cos(h)*l+Math.cos(h+Math.PI/2)*j;d.velocityy=Math.sin(h)*l+Math.sin(h+Math.PI/2)*j;f.velocityx=Math.cos(h)*i+Math.cos(h+Math.PI/2)*k;f.velocityy=Math.sin(h)*i+Math.sin(h+Math.PI/2)*k;d.nextx=d.nextx+=
d.velocityx;d.nexty=d.nexty+=d.velocityy;f.nextx=f.nextx+=f.velocityx;f.nexty=f.nexty+=f.velocityy;d.startPoint=new Point2D(d.nextx,d.nexty);f.startPoint=new Point2D(f.nextx,f.nexty);console.log("face>>>>>"+g)}}}}}};
Game.prototype.testNet=function(){for(var a,b=!1,e=this.balls[1],d=this.balls[2],g=this.balls[3],f=this.balls[4],h=0;h<this.balls.length;h++){a=this.balls[h];ball1=new Point2D(a.startPoint.x,a.startPoint.y);ball2=new Point2D(a.nextx,a.nexty);if(c1=intersectLineLine(new Point2D(e.x,e.y),new Point2D(e.x,e.y-this.field.goalHeight),ball1,ball2))a.velocityx*=-0.15,a.nextx=0<a.velocityx?e.x+a.radius:e.x-a.radius,b=!0;if(c2=intersectLineLine(new Point2D(d.x,d.y),new Point2D(d.x,d.y-this.field.goalHeight),
ball1,ball2))a.velocityx*=-0.15,a.nextx=0<a.velocityx?d.x+a.radius:d.x-a.radius,b=!0;if(c3=intersectLineLine(new Point2D(e.x,e.y-this.field.goalHeight),new Point2D(d.x,d.y-this.field.goalHeight),ball1,ball2))a.velocityy*=-0.15,a.nexty=0<a.velocityy?e.y-this.field.goalHeight+a.radius:e.y-this.field.goalHeight-a.radius,b=!0;if(c4=intersectLineLine(new Point2D(g.x,g.y),new Point2D(g.x,g.y+this.field.goalHeight),ball1,ball2))a.velocityx*=-0.15,a.nextx=0<a.velocityx?g.x+a.radius:g.x-a.radius,b=!0;if(c5=
intersectLineLine(new Point2D(f.x,f.y),new Point2D(f.x,f.y+this.field.goalHeight),ball1,ball2))a.velocityx*=-0.15,a.nextx=0<a.velocityx?f.x+a.radius:f.x-a.radius,b=!0;if(c6=intersectLineLine(new Point2D(g.x,g.y+this.field.goalHeight),new Point2D(f.x,f.y+this.field.goalHeight),ball1,ball2))a.velocityy*=-0.15,a.nexty=0<a.velocityy?g.y+this.field.goalHeight+a.radius:g.y+this.field.goalHeight-a.radius,b=!0;if(b)a.startPoint=new Point2D(a.nextx,a.nexty)}};Game.prototype.get_x=function(){return this._x};
Game.prototype.get_y=function(){return this._y};intersectCircleLine=function(a,b,e,d){var g,f=(d.x-e.x)*(d.x-e.x)+(d.y-e.y)*(d.y-e.y),h=2*((d.x-e.x)*(e.x-a.x)+(d.y-e.y)*(e.y-a.y)),a=h*h-4*f*(a.x*a.x+a.y*a.y+e.x*e.x+e.y*e.y-2*(a.x*e.x+a.y*e.y)-b*b);if(0>a)return!1;if(0==a)return!1;b=Math.sqrt(a);a=(-h+b)/(2*f);f=(-h-b)/(2*f);if((0>a||1<a)&&(0>f||1<f))return!1;0<=a&&1>=a&&(g=e.lerp(d,a));0<=f&&1>=f&&(g=e.lerp(d,f));return g};
intersectLineLine=function(a,b,e,d){var g=(d.x-e.x)*(a.y-e.y)-(d.y-e.y)*(a.x-e.x),f=(b.x-a.x)*(a.y-e.y)-(b.y-a.y)*(a.x-e.x),e=(d.y-e.y)*(b.x-a.x)-(d.x-e.x)*(b.y-a.y);if(0!=e)if(g/=e,f/=e,0<=g&&1>=g&&0<=f&&1>=f)a=new Point2D(a.x+g*(b.x-a.x),a.y+g*(b.y-a.y));else return!1;else return!1;return a};
function Keeper(a,b,e,d,g,f){0<arguments.length?(this.id=a,this.width=b,this.height=e,this.x=d,this.y=g,this.team=f):(this.id=0,this.width=90,this.height=30,this.y=this.x=0,this.team=null);this.angle=this.speed=0;this.mass=1E3}Keeper.prototype.draw=function(){return!0};
function Mouse(a){this.game=a;this.up_y=this.up_x=this.down_y=this.down_x=this.y=this.x=0;this.up=this.down=!1;var b=this;window.addEventListener("mousemove",function(a){b.mousemove(a)},!0);window.addEventListener("mousedown",function(a){b.mousedown(a)},!0);window.addEventListener("mouseup",function(a){b.mouseup(a)},!0)}Mouse.prototype.isOverBall=function(a){var b=!1;0<this.x&&0<this.y&&0<a.x&&0<a.y&&this.x>=a.x-a.radius&&this.x<=a.x+a.radius&&this.y>=a.y-a.radius&&this.y<=a.y+a.radius&&(b=!0);return b};
Mouse.prototype.isOverRect=function(a,b,e,d){var g=[];g[0]=a;g[1]=b;g[2]=e;g[3]=d;pt=new Point2D(this.x,this.y);a=!1;b=-1;e=g.length;for(d=e-1;++b<e;d=b)(g[b].y<=pt.y&&pt.y<g[d].y||g[d].y<=pt.y&&pt.y<g[b].y)&&pt.x<(g[d].x-g[b].x)*(pt.y-g[b].y)/(g[d].y-g[b].y)+g[b].x&&(a=!a);return a};Mouse.prototype.getX=function(){return this.x};Mouse.prototype.getY=function(){return this.y};Mouse.prototype.getDownX=function(){return this.down_x};Mouse.prototype.getDownY=function(){return this.down_y};
Mouse.prototype.getUpX=function(){return this.up_x};Mouse.prototype.getUpY=function(){return this.up_y};Mouse.prototype.getDown=function(){return this.down};Mouse.prototype.getUp=function(){return this.up};Mouse.prototype.mousemove=function(a){this.x=a.pageX+Math.abs(this.game.get_x())-this.game.canvas.offsetLeft;this.y=a.pageY+Math.abs(this.game.get_y())-this.game.canvas.offsetTop;console.log("> "+this.game.canvas.offsetTop+" : "+this.x+", "+this.y)};
Mouse.prototype.mousedown=function(a){if(!this.game.is_moving)document.body.style.cursor="auto";this.down_x=a.pageX+Math.abs(this.game.get_x())-this.game.canvas.offsetLeft;this.down_y=a.pageY+Math.abs(this.game.get_y())-this.game.canvas.offsetTop;this.down=!0;this.up=!1;this.up_y=this.up_x=0};
Mouse.prototype.mouseup=function(a){document.body.style.cursor="auto";this.up_x=a.pageX+Math.abs(this.game.get_x())-this.game.canvas.offsetLeft;this.up_y=a.pageY+Math.abs(this.game.get_y())-this.game.canvas.offsetTop;this.up=!0;this.down=!1;this.down_y=this.down_x=0;if(null!=this.game.selected_ball){if("move"!=this.game.selected_ball.id&&"rotate"!=this.game.selected_ball.id){this.game.selected_ball.startPoint=new Point2D(this.game.selected_ball.x,this.game.selected_ball.y);this.game.selected_ball.velocityx=
0.1*(this.game.selected_ball.x-this.up_x);this.game.selected_ball.velocityy=0.1*(this.game.selected_ball.y-this.up_y);if(this.game.selected_ball.velocityx>this.game.maxSpeed)this.game.selected_ball.velocityx=this.game.maxSpeed;if(this.game.selected_ball.velocityy>this.game.maxSpeed)this.game.selected_ball.velocityy=this.game.maxSpeed;this.game.running=!0;this.game.currentPlayer=this.game.selected_ball.id}}else if(this.game.is_moving)this.game.is_moving=!1;this.game.selected_ball=null};
function Point2D(a,b){if(0<arguments.length)this.x=a,this.y=b}Point2D.prototype.clone=function(){return new Point2D(this.x,this.y)};Point2D.prototype.add=function(a){return new Point2D(this.x+a.x,this.y+a.y)};Point2D.prototype.addEquals=function(a){this.x+=a.x;this.y+=a.y;return this};
Point2D.prototype.offset=function(a,b){var e=0;if(!(b.x<=this.x||0>=this.x+a.x)){var d;0<b.x*a.y-a.x*b.y?0>this.x?(d=this.x*a.y,d=d/a.x-this.y):0<this.x?(d=this.x*b.y,d=d/b.x-this.y):d=-this.y:b.x<this.x+a.x?(d=(b.x-this.x)*a.y,d=b.y-(this.y+d/a.x)):b.x>this.x+a.x?(d=(a.x+this.x)*b.y,d=d/b.x-(this.y+a.y)):d=b.y-(this.y+a.y);0<d&&(e=d)}return e};Point2D.prototype.rmoveto=function(a,b){this.x+=a;this.y+=b};Point2D.prototype.scalarAdd=function(a){return new Point2D(this.x+a,this.y+a)};
Point2D.prototype.scalarAddEquals=function(a){this.x+=a;this.y+=a;return this};Point2D.prototype.subtract=function(a){return new Point2D(this.x-a.x,this.y-a.y)};Point2D.prototype.subtractEquals=function(a){this.x-=a.x;this.y-=a.y;return this};Point2D.prototype.scalarSubtract=function(a){return new Point2D(this.x-a,this.y-a)};Point2D.prototype.scalarSubtractEquals=function(a){this.x-=a;this.y-=a;return this};Point2D.prototype.multiply=function(a){return new Point2D(this.x*a,this.y*a)};
Point2D.prototype.multiplyEquals=function(a){this.x*=a;this.y*=a;return this};Point2D.prototype.divide=function(a){return new Point2D(this.x/a,this.y/a)};Point2D.prototype.divideEquals=function(a){this.x/=a;this.y/=a;return this};Point2D.prototype.compare=function(a){return this.x-a.x||this.y-a.y};Point2D.prototype.eq=function(a){return this.x==a.x&&this.y==a.y};Point2D.prototype.lt=function(a){return this.x<a.x&&this.y<a.y};Point2D.prototype.lte=function(a){return this.x<=a.x&&this.y<=a.y};
Point2D.prototype.gt=function(a){return this.x>a.x&&this.y>a.y};Point2D.prototype.gte=function(a){return this.x>=a.x&&this.y>=a.y};Point2D.prototype.lerp=function(a,b){return new Point2D(this.x+(a.x-this.x)*b,this.y+(a.y-this.y)*b)};Point2D.prototype.distanceFrom=function(a){var b=this.x-a.x,a=this.y-a.y;return Math.sqrt(b*b+a*a)};Point2D.prototype.min=function(a){return new Point2D(Math.min(this.x,a.x),Math.min(this.y,a.y))};
Point2D.prototype.max=function(a){return new Point2D(Math.max(this.x,a.x),Math.max(this.y,a.y))};Point2D.prototype.toString=function(){return this.x+","+this.y};Point2D.prototype.setXY=function(a,b){this.x=a;this.y=b};Point2D.prototype.setFromPoint=function(a){this.x=a.x;this.y=a.y};Point2D.prototype.swap=function(a){var b=this.x,e=this.y;this.x=a.x;this.y=a.y;a.x=b;a.y=e};
function Team(a,b,e,d){this.slug=""!=a?a:"SPO";this.formation=""!=b?b:[[300,250],[450,250],[600,250],[750,250],[200,600],[350,600],[850,600],[700,600],[490,625],[570,615],[570,615],[570,615],[570,615],[570,615],[570,615],[570,615],[570,615]];this.player=e?e:null;this.color=d?d:"rgba(218, 37, 29, 0.5)"};