generator:
  class: sfDoctrineGenerator
  param:
    model_class:           socket
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          socket
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        object_actions:
          open:         ~
          dashboard:    ~
          _edit:        ~
          _delete:      ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
